name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy-development:
    name: Deploy to development
    environment:
      name: Development
    #if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to development

  deploy-testing:
    name: Deploy to testing
    needs: [ deploy-development ]
    environment:
      name: Testing
    #if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to testing

  deploy-staging:
    name: Deploy to staging
    needs: [ deploy-testing ]
    environment:
      name: Staging
    #if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging

  deploy-production:
    name: Deploy to production
    environment:
      name: Production
    needs: [ deploy-staging ]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production