name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy-development:
    name: Deploy to development
    environment:
      name: Development
    #if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - run: echo Deploy to development $(echo $GITHUB_SHA | head -c7)
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}
  deploy-testing:
    name: Deploy to testing
    needs: [ deploy-development ]
    environment:
      name: Testing
    #if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - run: echo Deploy to testing $(echo $GITHUB_SHA | head -c7)
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}
  deploy-staging:
    name: Deploy to staging
    needs: [ deploy-testing ]
    environment:
      name: Staging
    #if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging $(echo $GITHUB_SHA | head -c7)

  deploy-production:
    name: Deploy to production
    environment:
      name: Production
    needs: [ deploy-staging ]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production $(echo $GITHUB_SHA | head -c7)